# Generated by Django 3.2 on 2024-03-15 08:02

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to=mainapp.models.upload_to_sliders)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
