# Generated by Django 3.2 on 2024-02-27 09:35

from django.db import migrations, models
import django.db.models.deletion
import templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('icon', models.ImageField(upload_to=templates.models.upload_to_platform)),
            ],
            options={
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('cover', models.ImageField(upload_to=templates.models.upload_to_templates)),
                ('slides_num', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.category')),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=templates.models.upload_to_template_files)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.platform')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
            options={
                'verbose_name_plural': 'Template Files',
            },
        ),
    ]
