# Generated by Django 3.2 on 2024-03-15 07:55

from django.db import migrations, models
import django.db.models.deletion
import templates.models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20240305_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=templates.models.upload_to_template_gallery)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
            options={
                'verbose_name_plural': 'Template Gallery',
            },
        ),
    ]
